# Generated by Django 3.2.16 on 2023-11-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20231104_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.CharField(default='PKR', max_length=10, verbose_name='Price Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('check_with_seller', models.BooleanField(default=False, verbose_name='Check with Seller')),
                ('item_for_free', models.BooleanField(default=False, verbose_name='Item for Free')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=50, verbose_name='Condition')),
                ('title', models.CharField(max_length=255, verbose_name='Listing Title')),
                ('description', models.TextField(verbose_name='Listing Description')),
                ('seo_title', models.CharField(max_length=255, verbose_name='SEO Title')),
                ('seo_description', models.TextField(verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phone_visible', models.BooleanField(default=False, verbose_name='Phone Visible on Ad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_visible', models.BooleanField(default=False, verbose_name='Email Visible on Ad')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sellerinformation', verbose_name='Seller Information'),
        ),
    ]
