# Generated by Django 3.2.16 on 2023-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20231206_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='opening_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Opening Stock'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Price'),
        ),
    ]
