# Generated by Django 3.2.16 on 2023-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20231207_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='custom_price',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
    ]
