# Generated by Django 3.2.16 on 2023-12-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20231208_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField(verbose_name='Quantity Added')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='product.storeproduct')),
            ],
        ),
    ]
