# Generated by Django 3.2.16 on 2023-11-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20231105_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_geolocation',
            field=models.BooleanField(default=False, verbose_name='Use Geolocation'),
        ),
    ]
