# Generated by Django 3.2.16 on 2023-11-07 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinformation',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Login'),
        ),
        migrations.AddField(
            model_name='sellerinformation',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Member Since'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerinformation',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status (Online/Offline)'),
        ),
       migrations.AddField(
            model_name='sellerinformation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
