# Generated by Django 3.2.16 on 2023-12-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companyprofile_phone_numbers'),
        ('product', '0010_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.companyprofile'),
        ),
    ]
