# Generated by Django 3.2.16 on 2023-12-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companyprofile_phone_numbers'),
        ('product', '0011_customer_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.companyprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'mobile', 'email')},
        ),
    ]
