# Generated by Django 3.2.16 on 2023-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_categorycustomfield_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
