# Generated by Django 3.2.16 on 2023-11-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_customfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='custom_fields', to='product.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='categorycustomfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_custom_fields', to='product.category'),
        ),
    ]
