# Generated by Django 3.2.16 on 2023-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20231228_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
