# Generated by Django 3.2.16 on 2024-01-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Credit Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit'), ('partial', 'Partial')], default='cash', max_length=15, verbose_name='Payment Type'),
        ),
    ]
