# Generated by Django 3.2.16 on 2024-01-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20240101_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Opening Balance'),
        ),
    ]
