# Generated by Django 3.2.16 on 2023-11-27 07:17

from django.db import migrations, models

def set_city_id_null(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    Product.objects.filter(city_id__isnull=False).update(city_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20231108_1425'),
    ]

    operations = [
        migrations.RunPython(set_city_id_null),
    ]
