# Generated by Django 3.2.16 on 2024-01-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_customer_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('PCT', 'Percentage'), ('EVT', 'Event'), ('SSN', 'Seasonal'), ('CLR', 'Clearance')], max_length=3, verbose_name='Offer Type')),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage for percentage type, otherwise flat value', max_digits=5, verbose_name='Value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.product')),
            ],
        ),
    ]
