# Generated by Django 3.2.16 on 2023-11-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_customfield_is_searchable'),
        ('product', '0019_auto_20231127_1017'),
    ]

    operations = [
    ]
