# Generated by Django 3.2.16 on 2023-11-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('product', '0020_merge_20231127_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
