# Generated by Django 3.2.16 on 2024-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_manualtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_indexing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='needs_indexing',
            field=models.BooleanField(default=False),
        ),
    ]
