# Generated by Django 3.2.16 on 2023-11-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20231127_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.sellerinformation', verbose_name='Seller Information'),
        ),
    ]
