# Generated by Django 3.2.16 on 2023-11-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyprofile_phone_number'),
        ('product', '0022_alter_product_seller_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='companies.companyprofile'),
        ),
    ]
