# Generated by Django 3.2.16 on 2023-11-30 05:54

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20231130_0721'),
        ('locations', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='locations.address'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='working_categories',
            field=models.ManyToManyField(to='product.Category'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='working_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='product.Category', verbose_name='Working Categories'),
        ),
    ]
