# Generated by Django 3.2.16 on 2023-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20231130_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='branch_phone_numbers', to='companies.PhoneNumber'),
        ),
    ]
