# Generated by Django 3.2.16 on 2023-12-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='company_phone_numbers', to='companies.PhoneNumber'),
        ),
    ]
