# Generated by Django 3.2.16 on 2023-12-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_phone_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone_numbers',
        ),
    ]
