# Generated by Django 3.2.16 on 2023-11-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_customfield_is_searchable'),
        ('companies', '0004_auto_20231126_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.branch'),
        ),
    ]
