# Generated by Django 3.2.16 on 2023-11-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('companies', '0005_auto_20231126_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='locations.address'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.address'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
