# Generated by Django 3.2.16 on 2024-01-15 08:14

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companyprofile_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
