# Generated by Django 3.2.16 on 2023-11-28 06:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20231127_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
