# Generated by Django 3.2.16 on 2023-11-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_company'),
        ('companies', '0007_companyprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='working_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='product.Category', verbose_name='Working Categories'),
        ),
    ]
