# Generated by Django 3.2.16 on 2023-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20231104_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_description',
            field=models.TextField(blank=True, null=True, verbose_name='City Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_description',
            field=models.TextField(blank=True, null=True, verbose_name='Country Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='region_description',
            field=models.TextField(blank=True, null=True, verbose_name='Region Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='location',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title'),
        ),
    ]
