# Generated by Django 3.2.16 on 2023-11-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20231105_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
    ]
