# Generated by Django 3.2.16 on 2023-11-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20231105_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_for_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_geolocation',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
